// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "ncvxclustr_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// weights_init
List weights_init(const MatrixXi& idx, const MatrixXd dist);
RcppExport SEXP ncvxclustr_weights_init(SEXP idxSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXi& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const MatrixXd >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(weights_init(idx, dist));
    return rcpp_result_gen;
END_RCPP
}
