# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Calculate the Gaussian Kernel weights
#'
#'@export
weights_init <- function(idx, dist) {
    .Call('ncvxclustr_weights_init', PACKAGE = 'ncvxclustr', idx, dist)
}

